GET http://localhost:3001/api/phonebook

###
GET http://localhost:3001/api/phonebook/2

###
DELETE http://localhost:3001/api/phonebook/2

###
POST http://localhost:3001/api/phonebook
Content-Type: application/json

{
  "name": "Ada Lovelacel",
  "number": "617-372-5999"
}